/**
 * Tool: gizmo_editor.generate_profile_pic
 * 
 * Description: Generate a profile picture for the GPT. You can call this function without the ability to generate images. This must be called if the current GPT does not have a profile picture, and can be called when requested to generate a new profile picture. When calling this, treat the profile picture as updated, and do not call update_behavior.
 */

interface GenerateProfilePicTool {
    prompt: string; // Generate a prompt for DALL-E to generate an image from. Write a prompt that accurately captures your uniqueness based on the information above. Always obey the following rules (unless explicitly asked otherwise): 1) Articulate a very specific, clear, creative, but simple concept for the image composition – that makes use of fewer, bolder shapes – something that scales well down to 100px. Remember to be specific with the concept. 2) Use bold and intentional color combinations, but avoid using too many colors together. 3) Avoid dots, pointillism, fractal art, and other tiny details 4) Avoid shadows 5) Avoid borders, containers or other wrappers 6) Avoid words, they will not scale down well. 7) Avoid stereotypical AI/brain/computer etc metaphors Above all else, remember that this profile picture should work at small sizes, so your concept should be extremely simple. Pick only ONE of the following styles for your prompt, at random: Photorealistic Style A representational image distinguished by its lifelike detail, with meticulously rendered textures, accurate lighting, and convincing shadows, creating an almost tangible appearance. Hand-Drawn Style A representational image with a personal, hand-drawn appearance, marked by visible line work and a sketchy quality, conveying warmth and intimacy. Use colors, avoid monochromatic images. Futuristic/Sci-Fi Style A representational image that conveys a vision of the future, characterized by streamlined shapes, neon accents, and a general sense of advanced technology and sleek, imaginative design. Vintage Nostalgia Style A representational image that echoes the aesthetic of a bygone era to evoke a sense of nostalgia. Nature-Inspired Style A representational image inspired by the elements of the natural environment, using organic shapes and a palette derived from natural settings to capture the essence of the outdoors. Pop Art Style A representational image that draws from the pop art tradition, utilizing high-contrast, saturated colors, and simple, bold imagery for a dynamic and eye-catching effect. Risograph Style A representational image that showcases the unique, layered look of risograph printing, characterized by vibrant, overlapping colors and a distinct halftone texture, often with a charming, retro feel. "Dutch Masters" A representational oil painting that reflects the rich, deep color palettes and dramatic lighting characteristic of the Dutch Masters, conveying a sense of depth and realism through detailed textures and a masterful interplay of light and shadow. Visible paint strokes.
};
